---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Sharif Islam

jobtitle: "Associate Professor  \nSchool of Accountancy  \nSouthern Illinois University Carbondale" 
address: "Rehn Hall  · Room 216A · Carbondale, IL 62901"
fontawesome: yes
email: mdshariful.islam@siu.edu
web: msharifbd.netlify.app
github: msharifbd
twitter: MSharifIslam2
# phone: "318-516-0128"
# updated: yes  

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11.5pt
linkcolor: blue
urlcolor: blue
---


\vskip 0.2in

\noindent\rlap{\textbf{ACADEMIC APPOINTMENTS}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

**Southern Illinois University Carbondale**, Associate Professor \newline of Accountancy & Data Analytics \hfill 2025 - Current

**Southern Illinois University Carbondale**, Assistant Professor \newline of Accountancy & Data Analytics \hfill 2019 - 2025

**Louisiana Tech University**, Instructor, Accounting & Information Systems \hfill 2018-2019

**University of Dhaka**, Lecturer, Accounting & Information Systems \hfill 2013-2019

**Jahangirnagar University**, Lecturer, Accounting & Information Systems \hfill 2011-2013

\vskip 0.2in


\noindent\rlap{\textbf{EDUCATION}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

**Louisiana Tech University**, DBA - Emphasis: Accounting Information Systems \hfill 2019

**Eastern Illinois University**, MBA in Accountancy \hfill 2016

**University of Dhaka**, MBA in Accounting & Information Systems \hfill 2010

**University of Dhaka**, BBA in Accounting & Information Systems \hfill 2009

\vskip 0.2in

\noindent\rlap{\textbf{PROFESSIONAL CERTIFICATION}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

**Certified Public Accountant (CPA)**, License No 065.051430 (Illinois) 

**Certified Management Accountant (CMA)**, Membership No A-1131 (Bangladesh)


\vskip 0.2in

\noindent\rlap{\textbf{PROFESSIONAL EXPERIENCE}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

**KPMG Bangladesh**, Audit Assistant \hfill 2010

**SIEMENS Bangladesh**, Intern \hfill 2009 

\vskip 0.2in

\noindent\rlap{\textbf{ACADEMIC RESEARCH}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

## Publications 

1. Do Women on the Board Mitigate Cybersecurity Risks?, with Nusrat Farah, and Tom Stafford, *Journal of Information Systems*, 2026, Forthcoming. <https://doi.org/10.2308/ISYS-2025-042> 

2. Impact of Audit Committee Social Capital on the Adoption of COSO 2013 Framework, with  Nusrat Farah, Amanuel Tadesse, and William McCumber, *Advances in Accounting*, 2024, 64, 100685. <https://doi.org/10.1016/j.adiac.2023.100685>

3. CEO Network Connections and the Timeliness of Financial Reporting, with William McCumber, Nusrat Farah, and Huan Qiu, *Accounting Horizons*, 2023, 37 (4), 117-147. <https://doi.org/10.2308/HORIZONS-2021-056>

4. Accounting Data Analytics in `R`: A Case Study Using `tidyverse`, with Nusrat Farah and Tawei (David) Wang, *Journal of Emerging Technologies in Accounting*, 2023, 20 (2), 243-250. <https://doi.org/10.2308/JETA-2021-023> 

5. The `ChatGPT` Artificial Intelligence Chatbot: How Well Does It Answer Accounting Assessment Questions?, with David Wood, M. Achhpilia, M.T. Adams, N. Farah et al., *Issues in Accounting Education*, 2023, 38 (4), 81-108. <https://doi.org/10.2308/ISSUES-2023-013>.

6. The Spillover Effect of Focal Firms' Cybersecurity Breaches on Rivals and the Role of CIO: Evidence from Stock Trading Volume, with Tawei (David) Wang, Nusrat Farah, and Tom Stafford, *Journal of Accounting & Public Policy*, 2022, 41 (2), 106916. <https://doi.org/10.1016/j.jaccpubpol.2021.106916>.

7. Factors Associated with the Adoption of Data Analytics by Internal Audit Function (IAF), with Tom Stafford, *Managerial Auditing Journal*, 2022, 37(2), 193-223. <https://doi.org/10.1108/MAJ-04-2021-3090>. 

8. CEO Social Capital and the Value Relevance of Accounting Metrics: International Evidence, with William McCumber and Huan Qiu, *Corporate Ownership & Control*, 2022, 19(4), 80-102. <https://doi.org/10.22495/cocv19i4art8>.

9. Factors Associated with Security/Cybersecurity Audit by Internal Audit Function: An International Study, with Nusrat Farah and Tom Stafford, *Managerial Auditing Journal*, 2018, 33(4), 377-409. <https://doi.org/10.1108/MAJ-07-2017-1595>.

  
## Paper under Revision and Submission

1. Pitch Like a Man to Fit in? How Do Gender and Product Gender Congruence Affect Investors' Decisions?, with Nusrat Farah and Tom Stafford (Under Review in *Accounting, Organizations and Society*)


## Working Papers for Submission

1. Cognitive Foundations of Creativity: Linking Founding CEOs’ Cognitive Strengths to Creativity with Nusrat Farah (Ready to submit in a Journal).

2. Are Form 8-K Disclosures Informative to Auditors?, with Gopal Krishnan, Md Samsul Alam, and Prem Puwanenthiren (Ready to submit in a Journal).

3. Do Suppliers Care about Material Events? Evidence from Form 8-K Filings, with Muhammad Safiullah, Md Samsul Alam, and Prem Puwanenthiren (Ready to submit in a Journal).   

4. The Growing Role of Intelligent Automation in Auditing, with Tom Stafford, John Lauck, and Ajaan Khan (Ready to submit in a Journal).



## Work in Progress 

1. What Sounds Good is True: Impact of CEO’s Vocal Attractiveness and Managerial Deception on 
Analysts’ Behavior with Nusrat Farah and Doron Reichmann. 

2. Impact of Vocal Attractiveness on Auditors’ Fraud Risk Assessment, with Nusrat Farah 

3. Are Cybersecurity Risk Disclosures Costly? Evidence from SEC Final Rule 33-11216 with Nusrat Farah

4. Social Capital of Information Technology Executives and Data Breaches, with Tom Stafford, William McCumber, and Nusrat Farah.

5. Chief Audit Executives (CAE) Busyness and Audit Outcomes, with Nusrat Farah and Prem Puwanenthiren, and William McCumber.


\vskip 0.2in

\noindent\rlap{\textbf{CONFERENCE PRESENTATION, WORKSHOP \& PROCEEDINGS}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

## Research Conference Presentations & Workshops

1. **Islam, S.**, Farah, N., "What Do Firms Disclose Regarding Cybersecurity? Evidence From Item 1C of 10-K," *2025 16th Annual Pre-ICIS Workshop on Accounting Information Systems (SIGASYS)*. Nashville, TN: Association of Information Systems (AIS).

2. Stafford, T., Lauck, J., **Islam, M.S.**, Wang, T., Khan, A., "The Growing Role of Process Automation in Internal Auditing: Further Explorations of Grounded Theory," *2025 16th Annual Pre-ICIS Workshop on Accounting Information Systems (SIGASYS)*. Nashville, TN: Association of Information Systems (AIS). *2024 AAA AIS/SET Section Midyear Meeting*. Atlanta, GA: American Accounting Association.

3. Farah, N, **Islam, S**, Stafford, T, "Pitch Like a Man to Fit in? How Do Gender and Product Gender Congruence Affect Investors' Decisions," *2025 Accounting Behavior and Organizations (ABO) Research Conference*. Indianapolis, IN: American Accounting Association.

4. **Islam, S**, Farah, N, Stafford, T, "Do Women on the Board Mitigate Cybersecurity Risk?," *2025 AAA AIS/SET Section Midyear Meeting*. Boca Raton, FL: American Accounting Association. *2025 AAA Annual Meeting*. Chicago, IL: American Accounting Association.

5. **Islam, S**, Alam, S, Puwanenthiren, P, "How do Auditors Respond to Form 8-K Based Disclosures," *2024 AAA Annual Meeting*. Washington, DC: American Accounting Association.

6. **Islam, M.S**, Farah, N, McCumber, W, Stammerjohan, W, "Audit Committee Network Connections and the Timeliness of Financial Reporting," *2023 College of Business and Analytics (COBA) Seminar Series*, Southern Illinois University, Carbdondale, IL.

7. Stafford, T, Wang, T, **Islam, S**, "Grounding Theories of Audit Analytics," *2023 AAA AIS/SET Section Midyear Meeting*. Las Vegas, NV: American Accounting Association. 

8. Farah, N, **Islam, S**, Tadesse, A, and McCumber, W, "Impact of Audit Committee Social Capital on the Adoption of COSO 2013 Framework," *2022 AAA Midwest Region Meeting*. St. Louis, MO: American Accounting Association and *2022 Advances in Accounting Research Conference*. Bellingham, WA: Western Washington University. 

9. Li, T, **Islam, S**, and McCumber, W, "Audit Committee Connectedness and Financial Reporting Complexity (FRC)," *2022 AAA Southwest Region Meeting*. New Orleans, LA: American Accounting Association.

10. **Islam, M.S**, McCumber, W, Farah, N, and Stammerjohan, W, “Audit Committee Connectedness and Audit Outcomes,” *2021 SPARK Conference*: American Accounting Association; *Annual Meeting 2021*: American Accounting Association.

11. **Islam, M.S.**, Stafford, T, McCumber, W, and Farah, N, “Social Capital of Information Technology Executives and Data Breaches,” *2021 AAA AIS/SET Section Midyear Meeting*: American Accounting Association.

12. **Islam, M.S**, McCumber, W, Farah, N, and Qiu, H, “Executive Network Centrality and Audit Timeliness,” *2020 SPARK Conference*: American Accounting Association.

13. **Islam, M.S**, Stammerjohan, W, Stafford, T, and Farah, N, “Reaction of the Investors of Rival Firms to the Information Security Breach of Focal Firms: Evidence from Market Activity and Information Asymmetry,” *2020 AAA AIS/SET Section Midyear Meeting*. Orlando, FL: American Accounting Association.

14. **Islam, M.S**, and Stammerjohan, W, “20-F Reconciliation Requirement: A Review of the Literature before and after Its Elimination,” *2019 AAA Midwest Region Meeting*. Chicago, IL: American Accounting Association.

15. **Islam, M.S**, Stafford, T, and Stammerjohan, W, “Big Data Analytics Challenges & Internal Audit Function (IAF)’s Reliance on Big Data Analytics,” *2019 AAA AIS/SET Section Midyear Meeting*. San Antonio, TX: American Accounting Association and *2019 AAA Southwest Region Meeting*. Houston, TX: American Accounting Association.

## Education Conference Attendance

1. Accounting Accreditation Seminar, AACSB, February 26, 2026, Nashville, IL.
2. Preparing for a Successful CIR Visit Workshop, AACSB, February 20, 2026, Southern Illinois University, Carbondale, IL. 
3. 2022 Audit Educators' Bootcamp, June 21-23, 2022, Chicago, IL. 
4. 2021 Accounting Information Systems Bootcamp Integrating Disruptive Technologies into the Accounting Curriculum, June 3-4, 2021, *Virtual Meeting*. 

## Conference Proceedings 

1. **Islam, M.S**, and Lee, J., “Internal Audit Function (IAF)’s Competencies and Cybersecurity Audit,” *Proceedings of the 2018 Americas Conference for Information Systems*. New Orleans, LA: Association for Information Systems.

2. Stafford, T., Wang, T., Syler, R., and **Islam, M.S.**, “Analytics for Accounting Information Systems Applications: A Research Panel,” *Proceedings of the 2018 Americas Conference for Information Systems*. New Orleans, LA: Association for Information Systems.

3. **Islam, M.S**, and Stafford, T., “Information Technology (IT) Integration and Cybersecurity/Security: The Security Savviness of Board of Directors,” *Proceedings of the 2017 Americas Conference for Information Systems*. Boston, MA: Association for Information Systems.

4. **Islam, M.S**, Jiang, R., and Stafford, T., “The Role of Accounting and Professional Associations in IT Security Auditing: A Research Panel,” *Proceedings of the 2017 Americas Conference for Information Systems*. Boston, MA: Association for Information Systems.

\vskip 0.2in

\noindent\rlap{\textbf{BOOK IN PROGRESS}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

[**Analytics for Accounting Data**](https://analyticsforaccountingdata.netlify.app/) (The book is under progress).


\vskip 0.2in

\noindent\rlap{\textbf{TEACHING EXPERIENCE}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

## Graduate Courses 

*Southern Illinois University Carbondale* - 

* ACCT561 Analytics for Accounting Data (Spring 2025-2026) (Residential and Online)
* BA529A Accounting Analytics (Spring 2026) (Online)
* ACCT591 Independent Study (Spring 2020)

## Undergraduate Courses 

*Southern Illinois University Carbondale* - 

* ACCT460 Auditing (Fall 2019-2025; Spring 2020-2025)
* ACCT431 Advanced Cost Accounting (Fall 2025)
* ACCT360 Accounting Information Systems (Fall 2019-2024; Spring 2020-2021, 2025)
* ACCT331 Cost Accounting (Spring 2025)
* BSAN405 Machine Learning in Business (Spring 2022-2026)

*Louisiana Tech University* - 

* ACCT201 Principle of Financial Accounting (Winter 2019, Spring 2019, Summer 2019)
* CIS310  Principle of Information Systems  (Fall 2018, Winter 2019, Spring 2019)

*University of Dhaka* - 

* Business Statistics I, Auditing I.

*Jahangirnagar University* - 

* Business Mathematics, Financial Accounting, Advanced Accounting, Business Communication, Introduction to Business.


\vskip 0.2in

\noindent\rlap{\textbf{HONORS \& AWARDS}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

* 2024 Notable Contribution to the Literature Award by the AIS Section of the American Accounting Association (AAA) for the paper titled "The `ChatGPT` Artificial Intelligence Chatbot: How Well Does It Answer Accounting Assessment Questions?"

* Summer Faculty Research Grant (SFRG) 2023 ($5,000), School of Accountancy, College of Business & Analytics, Southern Illinois University Carbondale.

* Summer Faculty Research Grant (SFRG) 2022 ($4,000), College of Business & Analytics, Southern Illinois University Carbondale.

* Best Research Paper Award 2021, American Accounting Association (AAA) 2021 Spark: Meeting of the Regions - Midwest Region on May 24-26, 2021.

* Best Research Paper Award 2020, American Accounting Association (AAA) AIS/SET Section Midyear Meeting on January 23-25, 2020, Orlando, FL.

* FBD’s Distinguished Paper Award 2019, American Accounting Association (AAA) Southwest Region/FBD Meeting on March 13-16, 2019, Houston, TX.

* DBA Outstanding Research Award 2019, College of Business, Louisiana Tech University.

* Doctoral Consortium Fellow: 2018 International Conference for Information Systems (ICIS) – Only 20 students are invited from the USA.

* Barnes Scholarship for 2018-2019 ($4000), Louisiana Tech University.

* Virginia Thompson Scholarship 2018–2019 ($5000), Louisiana Tech University.

* Virginia Thompson Scholarship 2017–2018 ($1250), Louisiana Tech University.

* Mansingh Memorial MBA Scholarship 2015 ($500), School of Business, Eastern Illinois University

* Foster C. Rinefort Scholarship 2015 ($500), School of Business, Eastern Illinois University.

* Accounting Advisory Board Scholarship 2014 ($1000), School of Business, Eastern Illinois University.

* Scholarship for Becker Professional Education’s CPA Exam Review 2014, Becker Professional Education, USA.

* Dean’s Merit List Award 2010, Faculty of Business Studies, University of Dhaka.

* Excellence Award 2009, ABM Khalid Memorial Trust, for “Best Male Student” in BBA Program in University of Dhaka.

* Accounting Alumni Scholarship 2008, Department of Accounting & Information Systems, University of Dhaka.


\vskip 0.2in

\noindent\rlap{\textbf{SERVICES}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

## Services to the Profession 

*Journal Reviewer/Editor*

* *International Journal of Auditing* 2025. 
* *International Journal of Accounting Information Systems* 2025.
* *Journal of Information Systems* 2024, 2021 and 2020.
* *Information Systems Frontiers* 2021.
* *International Journal of Computer Auditing* 2024, 2022.
* *The DATA BASE for Advances in Information Systems* 2021.
* *Managerial Auditing Journal* 2018 (Cybersecurity Special Issue), 2023.
* Senior Editor (SE) for *The DATA BASE for Advances in Information Systems* 2021.

*Conference Reviewer/Discussant/Committee Service*

* American Accounting Association (AAA) Annual Meeting 2026, 2025, and 2024.
* American Accounting Association (AAA) AIS/SET Midyear Meeting 2026, 2025, 2019.
* American Accounting Association (AAA) Accounting, Behavior, and Organizations (ABO) Section Midyear meeting 2025. 
* American Accounting Association (AAA) Auditing Section Midyear Meeting 2025.
* Member of Education Committee of Auditing Section of American Accounting Association (AAA) 2024-2027
* American Accounting Association (AAA) Midwest Region Meeting 2022, 2019, and 2018.
* American Accounting Association (AAA) SPARK Meeting 2021.
* American Accounting Association (AAA) AIS/SET Midyear Meeting 2020.
* American Accounting Association (AAA) Midwest Region Meeting 2019.
* American Accounting Association (AAA) AIS/SET Midyear Meeting 2019.
* International Conference on Information Systems (ICIS) 2019.
* Americas Conference on Information Systems (AMCIS) 2019.
* 2018 Pre-ICIS Workshop on Information Security and Privacy.
* International Conference on Information Systems (ICIS) 2018.
* Americas Conference on Information Systems (AMCIS) 2018.
* Americas Conference on Information Systems (AMCIS) 2017.


## Services to the University  

*Committee Services* 

* Member of Faculty Search Committee 2026, School of Accountancy, Southern Illinois University of Carbondale.
* Assessment of Learning (AOL) representative 2026 - 2027 from School of Accountancy, Southern Illinois University Carbondale.
* Member of Strategic Planning Committee 2025, College of Business & Analytics, Southern Illinois University Carbondale.
* Member of Faculty Research Committee (FRC) 2025, College of Business & Analytics, Southern Illinois University Carbondale. 
* Member of Doctoral Program Committee (DPC) 2025, College of Business & Analytics, Southern Illinois University Carbondale. 
* Member of Scholarship Review Panel (Fellowship Committee) 2025, Graduate School, Southern Illinois University Carbondale.
* Member of Steering Committee of School of Accountancy - SIUC 2020-2021.
* Member of School of Accountancy Curriculum Revision Committee - SIUC 2021.

*Other Services* 

* Advisor to Accounting Society (RSO)2025-2026, School of Accountancy, Southern Illinois University Carbondale
* Conducting a Seminar on "How to Showcase Your Portfolio Using Your Own Website" Organized by Accounting Society of School of Accountancy, SIUC (Fall 2025)
* Presentation on Data Analytics in SIUC Day, Fall 2024.
* Mentor in 2024 Junior Science and Humanities Symposium (JSHS), STEM Education Research Center, Southern Illinois University Carbondale. 
* Representing School of Accountancy in 2025, 2024, 2022, 2021, and 2019 SIUC Open House.
* Faculty Advisor of Bangladesh Student Association (BSA) - SIUC 2021 - 2022.
* Representing School of Accountancy in Business Analytics Launching Program of College of Business in Chicago, IL on November 13, 2019.
* Attending Board Meeting of Pontikes Center for Advanced Analytics and Artificial Intelligence in Chicago, IL on November 14, 2019.
* Judge for 2016 Annual Undergraduate/Graduate Research Symposium in Louisiana Tech University, 2016.

\vskip 0.2in

\noindent\rlap{\textbf{AFFILIATIONS \& MEMBERSHIPS}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

* American Accounting Association (AAA)
* American Accounting Association (AAA) - Audit Section
* American Accounting Association (AAA) - Accounting Information Systems Section
* American Accounting Association (AAA) - Financial Accounting & Reporting Section

\vskip 0.2in

\noindent\rlap{\textbf{COMPUTER \& SOFTWARE SKILLS}}\rule[9pt]{\textwidth}{.10pt}

\vspace{-5truemm}

* Advanced Knowledge in `R` Programming, including `RMarkdown`, `Quarto`, bookdown, and blogdown.
* Intermediate Knowledge in `Python` Programming. 
* SAS, STATA, SPSS, AMOS.
* Programming Language – Visual Basic and Java.
* Databases - PostgreSQL and DuckDB.

\vspace{-5truemm}

\noindent\rlap{\textbf{}}\rule[9pt]{\textwidth}{.10pt}

